services:
  app:
    build: .
    image: assistialab-agents:dev
    container_name: assistialab-agents
    command: python -c "import assistialab_agents as a; print(a.hello('Compose'))"
    # volumes:
    #   - .:/app:delegated
    # environment:
    #   - EXAMPLE_VAR=value
