services:
  app:
    build: .
    image: assistialab-agents:dev
    container_name: assistialab-agents
    ports:
      - "8000:8000"

    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
        - path: ./requirements.txt
          action: rebuild
        - path: ./Dockerfile
          action: rebuild
