line-length = 100
target-version = "py311"

[lint]
select = ["E","F","I","B","UP","SIM","PL","ANN","TID","RUF"]
ignore = ["E501"]  # keep for now

[format]
quote-style = "preserve"
indent-style = "space"
line-ending = "auto"
